version: "2"

services:

  postgres:
    image: postgres:13
    command: postgres -c 'max_connections=200'
    container_name: postgres
    env_file: postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.2
        

  chainlink_node1:      
    image: ferru97/chainlink-diabolik
    container_name: chainlink_node1
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink1?sslmode=disable
      - PEER_ID=p2p_12D3KooWALTnn7MtMcwhvYbZ4m5W6f7pKDFJGjHnQJyGX1d4RUHe
      - CHAINLINK_PORT=6691
      - CLIENT_NODE_URL=http://localhost:6691
      - P2P_LISTEN_PORT=3002
    ports:
      - 7001:6691
    volumes:
      - ./volumes/chainlink1:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_1.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_1.toml:/home/root/data_job.toml
    links:
      ###- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.3

  chainlink_node2:      
    image: ferru97/chainlink-diabolik
    container_name: chainlink_node2
    command: chainlink local n -p /chainlink/.password -a /chainlink/.api
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink:chainlink123@postgres:5432/chainlink2?sslmode=disable
      - CHAINLINK_PORT=6692
      - CLIENT_NODE_URL=http://localhost:6692
      - P2P_LISTEN_PORT=3003
    ports:
      - 7002:6692
    volumes:
      - ./volumes/chainlink2:/chainlink
      - ./scripts/chainlink_login.sh:/home/root/chainlink_login.sh
      - ./scripts/chainlink_delete_job.sh:/home/root/chainlink_delete_job.sh
      - ./scripts/jobs/job_ocr_oracle_2.toml:/home/root/ocr_job.toml
      - ./scripts/jobs/job_data_oracle_2.toml:/home/root/data_job.toml
    links:
      ###- "geth"
      - "postgres"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.4


    
  web_server:
    build:
      context: web_server/
      dockerfile: Dockerfile
    image: web_server
    container_name: web_server
    env_file:
      - ./web_server.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      chainlink_net:
        ipv4_address: 10.5.0.6
    

      
networks:
  chainlink_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
      
