
type = "offchainreporting"
schemaVersion = 1
contractAddress = "0x61D12EEA21972B297aD92a0fF94aD516190C3ac2"
p2pPeerID = "12D3KooWBorAGwzBcvyzvNworgqt3WAoPBS7myMyLFKfmzSqHY97"
p2pBootstrapPeers = [
"/ip4/10.5.0.15/tcp/3002/p2p/12D3KooWSHeFvD8SDPY4a1vec3aMCujcVTakHVBjwixungR2fiCR"
]
isBootstrapPeer = false
keyBundleID = "373e61a793b660e02eee09cd4a5791f6f8390f5eb15cd0e5c054b9d0cdb8ddae"
transmitterAddress = "0x6BDfa71d13d860701aE14f0d6a0BDc533ba61010"
observationTimeout = "20s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    // data source 1
    eth_spent_hash          [type=http method=GET url="http://10.5.0.6:3000/getDataHash?reqmanager=0x11088f37e15b2e152808D919EbA0FC53c93C5c96&oid=0x6BDfa71d13d860701aE14f0d6a0BDc533ba61010"]

    eth_spent_hash
"""
maxTaskDuration = "0s"
externalJobID = "0eec7e1d-d0d2-476c-a1a8-72dfb6633f06"
