
type = "offchainreporting"
schemaVersion = 1
contractAddress = "0x7aFC462040e316F558b9d18137F62b1e63fb9656"
p2pPeerID = "12D3KooWKjFr5YWYdNtej6FhwRAqNzi3mJmQH8DZa4BvBMciEuSw"
p2pBootstrapPeers = [
"/ip4/10.5.0.15/tcp/3002/p2p/12D3KooWSHeFvD8SDPY4a1vec3aMCujcVTakHVBjwixungR2fiCR"
]
isBootstrapPeer = false
keyBundleID = "5c26bdafc5bb0766387485b7c965b1889da58a2ab75a1b9ebd749af7c7235704"
transmitterAddress = "0x2Be2Ba2996e0F4eD0bfDC9476c04811bc08c780a"
observationTimeout = "20s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    // data source 1
    eth_spent_hash          [type=http method=GET url="http://10.5.0.6:3000/getDataHash?reqmanager=0xa2217E0ee2dd9Db51489F30EDBea42cb5EDD3d40&oid=0x2Be2Ba2996e0F4eD0bfDC9476c04811bc08c780a"]

    eth_spent_hash
"""
maxTaskDuration = "0s"
externalJobID = "0eec7e1d-d0d2-476c-a1a8-72dfb6633f06"
