
type = "offchainreporting"
schemaVersion = 1
contractAddress = "0x7aFC462040e316F558b9d18137F62b1e63fb9656"
p2pPeerID = "12D3KooWH1UkpkQ9XtkB6HhzjPeghAAq9Q4oNqyA69qGX1oicEd1"
p2pBootstrapPeers = [
"/ip4/10.5.0.15/tcp/3002/p2p/12D3KooWSHeFvD8SDPY4a1vec3aMCujcVTakHVBjwixungR2fiCR"
]
isBootstrapPeer = false
keyBundleID = "b6f95e0c7db9416bf0e5213592c27043417a11ab626ca8df091f058a53524241"
transmitterAddress = "0x35E86089a1EA9BC6a6eeAD55DC57D00E4f7a4D28"
observationTimeout = "20s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    // data source 1
    eth_spent_hash          [type=http method=GET url="http://10.5.0.6:3000/getDataHash?reqmanager=0xa2217E0ee2dd9Db51489F30EDBea42cb5EDD3d40&oid=0x35E86089a1EA9BC6a6eeAD55DC57D00E4f7a4D28"]

    eth_spent_hash
"""
maxTaskDuration = "0s"
externalJobID = "0eec7e1d-d0d2-476c-a1a8-72dfb6633f06"
