
type = "offchainreporting"
schemaVersion = 1
contractAddress = "0x7aFC462040e316F558b9d18137F62b1e63fb9656"
p2pPeerID = "12D3KooWF5XvGzXTbwizej7frYaW866EfpbRsKLxptgVi6L5pyos"
p2pBootstrapPeers = [
"/ip4/10.5.0.15/tcp/3002/p2p/12D3KooWSHeFvD8SDPY4a1vec3aMCujcVTakHVBjwixungR2fiCR"
]
isBootstrapPeer = false
keyBundleID = "7a9c203556baee32cdd4b7829d7fb461afbb4c2fa7fb581e901042a3b3a969c8"
transmitterAddress = "0xf4A5B3cbe74BE7c47190C5d2F0E2A9c5b6ED8fC8"
observationTimeout = "20s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    // data source 1
    eth_spent_hash          [type=http method=GET url="http://10.5.0.6:3000/getDataHash?reqmanager=0xa2217E0ee2dd9Db51489F30EDBea42cb5EDD3d40&oid=0xf4A5B3cbe74BE7c47190C5d2F0E2A9c5b6ED8fC8"]

    eth_spent_hash
"""
maxTaskDuration = "0s"
externalJobID = "0eec7e1d-d0d2-476c-a1a8-72dfb6633f06"
