
type = "offchainreporting"
schemaVersion = 1
contractAddress = "0x7aFC462040e316F558b9d18137F62b1e63fb9656"
p2pPeerID = "12D3KooWDyQhEMN9Ysndq7nEDcwg1ZVe2TwmFuh7Hs6w66uXCix6"
p2pBootstrapPeers = [
"/ip4/10.5.0.15/tcp/3002/p2p/12D3KooWSHeFvD8SDPY4a1vec3aMCujcVTakHVBjwixungR2fiCR"
]
isBootstrapPeer = false
keyBundleID = "b2a9434f97ff6a5a9dc6b055598c6765d22ab0eaa62bfb5d72d4eca9697c38b2"
transmitterAddress = "0xAA7964FDac7bd564078FccB614B22757F786E851"
observationTimeout = "20s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    // data source 1
    eth_spent_hash          [type=http method=GET url="http://10.5.0.6:3000/getDataHash?reqmanager=0xa2217E0ee2dd9Db51489F30EDBea42cb5EDD3d40&oid=0xAA7964FDac7bd564078FccB614B22757F786E851"]

    eth_spent_hash
"""
maxTaskDuration = "0s"
externalJobID = "0eec7e1d-d0d2-476c-a1a8-72dfb6633f06"
