
type = "offchainreporting"
schemaVersion = 1
contractAddress = "0xcc9d88e18b45fc8c3a881AB7C15a824cE9570cB8"
p2pPeerID = "12D3KooWErCK2guFZDQWb22Q9svxQPvhfSkd6GLjd783B1Ew6DPa"
p2pBootstrapPeers = [
"/ip4/151.45.238.85/tcp/3004/p2p/12D3KooWM1Jr6o9g5oZC5UYWAkBcmKajTrG85v5WYnE1q5MigmsM"
]
isBootstrapPeer = false
keyBundleID = "3678aa3c3d792192d979de11487dc677d780cc59eb208fee90a4d2a22846d4b2"
transmitterAddress = "0x8487EB719a6535c2D7aDBDD10F8cb07EdB1bff3F"
observationTimeout = "20s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    // data source 1
    eth_spent_hash          [type=http method=GET url="http://10.5.0.6:3000/getDataHash?reqmanager=0xcEa01A70260d5d3f3c07DA33082c8FC24b6B716b&oid=0x8487EB719a6535c2D7aDBDD10F8cb07EdB1bff3F"]

    eth_spent_hash
"""
maxTaskDuration = "0s"
externalJobID = "0eec7e1d-d0d2-476c-a1a8-72dfb6633f06"
